version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: deliciousfood-postgis
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
