spring:
  application:
    name: DeliciousFood

  data:
    mongodb:
      # Atlas 연결 (DB 이름: delicious)
      uri: "mongodb+srv://2071199:dydrkfl!23@cluster0.b72qlr9.mongodb.net/delicious?retryWrites=true&w=majority&appName=Cluster0"

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: WARN
